services:
  infdb_service:
    build: 
      context: ./infdb_service
      dockerfile: Dockerfile
    ports:
      - "5003:5000"
    environment:
      - FLASK_ENV=production
    networks:
      - backend_network

  measures_service:
    build: 
      context: ./measures_service
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production
    networks:
      - backend_network

  sensor_service:
    build: 
      context: ./sensor_service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    networks:
      - backend_network

  auth_service:
    build: 
      context: ./auth_service
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    environment:
      - FLASK_ENV=production
    networks:
      - backend_network

  alert_service:
    build: 
      context: ./alert_service
      dockerfile: Dockerfile
    ports:
      - "5004:5000"
    environment:
      - FLASK_ENV=production
      - EMAIL_ADDRESS=kogiaalerts@gmail.com
      - EMAIL_PASSWORD=kogia9030K
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=465
      - ALERT_RECEIVER=yitaw30211@simerm.com
      - LIMITS_API_URL=https://measures-service-production.up.railway.app/api/measures
      - INFLUX_URL=http://infdb_service:8086
      - INFLUX_TOKEN=YY2G3o8Du9uFpXeIn1SX4wSIYO32R3UArJbEgzCpyrbyE3zGGEiIdFzcVv1EvLa33TbFdsu_XENNtOhTy7W
      - INFLUX_ORG=3dcfd1ba132d8ffe
      - INFLUX_BUCKET=KOGIA_TEST5
    networks:
      - backend_network

  modeling_service:
    build: 
      context: ./modeling_service
      dockerfile: Dockerfile
    ports:
      - "5005:5000"
    environment:
      - FLASK_ENV=production
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge